### ISSUE TITLE
Memory leaks in meshlink_open

### ISSUE THREAD

**Issue by a-krebs** [meshlink/meshlink#19]
Output from llvm memory sanitizer:

```
Direct leak of 2343 byte(s) in 71 object(s) allocated from:
    #0 0x1ef04f6 in __interceptor_strdup (/home/work/tmp/linux_clang_build_6f8d468/everbase_test_all+0x1ef04f6)
    #1 0x6e4cf71 in xstrdup /home/build/jenkins/workspace/backend_linux_ubuntu-14.04_x86-64_clang/oak/build_work/backend/src/backend-build/external_projects/src/meshlink/src/./xalloc.h:48:12
    #2 0x6e4d000 in get_config_string /home/build/jenkins/workspace/backend_linux_ubuntu-14.04_x86-64_clang/oak/build_work/backend/src/backend-build/external_projects/src/meshlink/src/conf.c:167:12
    #3 0x6e55123 in get_name /home/build/jenkins/workspace/backend_linux_ubuntu-14.04_x86-64_clang/oak/build_work/backend/src/backend-build/external_projects/src/meshlink/src/net_setup.c:215:2
    #4 0x6e41414 in meshlink_open /home/build/jenkins/workspace/backend_linux_ubuntu-14.04_x86-64_clang/oak/build_work/backend/src/backend-build/external_projects/src/meshlink/src/meshlink.c:933:25
    #5 0x3d0730e in meshlink::mesh::open(char const*, char const*, char const*, dev_class_t) /home/build/jenkins/workspace/backend_linux_ubuntu-14.04_x86-64_clang/oak/build_work/backend/src/backend-build/external_projects/include/meshlink/meshlink++.h:152:13
```

I suspect the return value from `get_name` must be deallocated.

**Comment by a-krebs** [comment]
Fixed with 0f516b0b3a7e7bb67daee6b4a87aee9ad675ab37
